# Generated by Django 3.2.9 on 2021-12-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_company_job_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company_id',
            new_name='company',
        ),
    ]
