# Generated by Django 3.2.9 on 2021-12-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
