# Generated by Django 3.2.9 on 2021-12-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteer_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='curriculum_vitae',
            field=models.FileField(upload_to='CV'),
        ),
    ]
