# Generated by Django 3.2.9 on 2021-12-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='curriculum_vitae',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
