# Generated by Django 3.2.9 on 2021-12-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_closed'),
        ('volunteers', '0003_alter_volunteer_curriculum_vitae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='jobs',
            field=models.ManyToManyField(null=True, to='jobs.Job'),
        ),
    ]
