# Generated by Django 3.2.9 on 2021-12-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_closed'),
        ('volunteers', '0005_alter_volunteer_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.Job'),
        ),
    ]
